kibot:
  version: 1
global:
  out_dir: output
preflight:
  check_zone_fills: true
  erc: true
  # DRC disabled while artwork unfinished
  drc: false

outputs:
  - name: Info
    type: info

  - name: Report
    type: report
